# Setup
title:               Karthik Nukala
tagline:             'The Harker School Class of 2020'
description:         "I am a high school student at The Harker School in San Jose, CA. I am an avid computer scientist and a member of Carnegie Mellon University's School of Computer Science Class of 2024"
url:                 https://karthiknukala.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Karthik Nukala
  url:               https://karthiknukala.github.io
  email:             karthik.nukala02@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
